function out1 = region_sensitivity_K1(K1)
%REGION_SENSITIVITY_K1
%    OUT1 = REGION_SENSITIVITY_K1(K1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 19:31:29

t2 = K1.*4.0e-11;
t3 = t2-1.0./2.5e2;
t4 = 1.0./t3;
t5 = K1.*1.0e-8;
t6 = t5-2.0./2.5e1;
t7 = 1.0./t3.^2;
out1 = [t3.*(t4.*3.68e-3-K1.*t7.*1.472e-13).*2.717391304347826e2;(K1.*t3.*(t4.*2.0e-4-t6.*t7.*8.0e-7).*5.0e-5)./t6];
