function out1 = region_sensitivity_r2(r2)
%REGION_SENSITIVITY_R2
%    OUT1 = REGION_SENSITIVITY_R2(R2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 19:31:28

t2 = r2.*(1.0./2.0e1);
t3 = t2-6.0e-6;
t4 = 1.0./t3;
t5 = 1.0./t3.^2;
t6 = r2-1.5e-3;
out1 = [t3.*(t4.*6.9e3-r2.*t5.*3.45e2).*1.449275362318841e-4;(r2.*t3.*(t4.*2.0e4-t5.*t6.*1.0e3).*5.0e-5)./t6];
