function out1 = region_sensitivity_a1(a1)
%REGION_SENSITIVITY_A1
%    OUT1 = REGION_SENSITIVITY_A1(A1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 19:31:29

t2 = a1.*6.0e2;
t3 = t2-1.0./2.5e2;
t4 = a1.*3.2e4;
t5 = t4-1.0./2.5e2;
t6 = 1.0./t3.^2;
out1 = [(a1.*t3.*(t5.*t6.*9.0e7-4.8e9./t3).*(-6.666666666666667e-6))./t5;a1.*t6.*(a1.*(6.0e1./1.57e2)-2.547770700636943e-6).*-9.42e5];
