function out1 = solution_sensitivity_r2(r2)
%SOLUTION_SENSITIVITY_R2
%    OUT1 = SOLUTION_SENSITIVITY_R2(R2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 18:59:27

t2 = r2.*(1.0./5.0);
t3 = t2-2.4e-5;
t4 = r2.*2.0;
t5 = t4-3.0./1.0e3;
t6 = 1.0./t3.^2;
t7 = 1.0./t3;
out1 = [t3.*(t7.*1.38e4-r2.*t6.*2.76e3).*7.246376811594203e-5;(r2.*t3.*(t7.*4.0e4-t5.*t6.*4.0e3).*5.0e-5)./t5];
