function out1 = solution_sensitivity_r1(r1)
%SOLUTION_SENSITIVITY_R1
%    OUT1 = SOLUTION_SENSITIVITY_R1(R1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 16:02:27

t2 = r1.*(4.0./2.5e1);
t3 = t2-6.4e-4;
t4 = r1.*(8.0./2.5e1);
t5 = t4-2.4e-5;
t6 = 1.0./t5.^2;
t7 = 1.0./t5;
out1 = [(r1.*t5.*(t7.*2.4e4-t3.*t6.*4.8e4).*6.666666666666667e-6)./t3;t5.*(t7.*6.28e4-r1.*t6.*2.0096e4).*1.592356687898089e-5];
