function out1 = solution_sensitivity_K2(K2)
%SOLUTION_SENSITIVITY_K2
%    OUT1 = SOLUTION_SENSITIVITY_K2(K2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    28-Feb-2016 18:59:28

t2 = K2.*1.6e-9;
t3 = t2-1.0./1.25e2;
t4 = K2.*6.0e-11;
t5 = t4-2.0./1.25e2;
t6 = 1.0./t5;
t7 = 1.0./t5.^2;
out1 = [(K2.*t5.*(t6.*2.4e-4-t3.*t7.*9.0e-6).*6.666666666666667e-6)./t3;t5.*(t6.*7.85e-3-K2.*t7.*4.71e-13).*1.273885350318471e2];
